package `in`.isro.sih26173.itantramessage.data.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PublicKey
import java.security.interfaces.ECPublicKey
import java.security.spec.ECGenParameterSpec
import java.security.spec.X509EncodedKeySpec
import javax.crypto.KeyAgreement
import javax.crypto.SecretKey

/**
 * The JCA provider name for the hardware-backed keystore.
 *
 * At file scope rather than in the companion because a primary constructor's default argument
 * cannot see a companion object of the class it belongs to -- the companion is not initialised
 * while the constructor signature is being resolved. Declaring it here is the whole reason the
 * class compiles.
 */
private const val KEYSTORE_PROVIDER = "AndroidKeyStore"

/**
 * Deliberately distinct from the AES alias prefix in `EncryptionManager`.
 *
 * File scope for the same reason as [KEYSTORE_PROVIDER].
 */
private const val DEFAULT_IDENTITY_ALIAS = "itantra_msg.identity.ec"

/**
 * This device's long-term identity, used to agree a message key with a peer.
 *
 * ## Why this exists
 *
 * Before it, the app had no shared secret with anyone. Each device generated its own AES key in
 * its own Keystore and encrypted with it, so a message from the realme arrived on the Samsung
 * and could not be opened: the receiver asked its Keystore for *its* key, which is a different
 * key. On hardware that surfaced as a message that rendered "Could not read that message". The
 * 95 tests could not find it, because encrypt and decrypt were each correct and the missing
 * thing was not a function at all -- it was an agreement.
 *
 * ## What is and is not authenticated
 *
 * **This is not an authenticated key exchange.** Nothing here signs anything, so a device in
 * range could insert its own key pair and read traffic. The app's answer is that the link is
 * RFCOMM to a **bonded** peer: the Bluetooth bond already authenticated the radio addresses
 * using a link key the platform keeps, so a frame arriving on this socket came from the phone
 * the user paired with. That is a real defence, and it is the *only* one this class provides.
 *
 * It is recorded here rather than left implicit because "we use ECDH" reads as much stronger
 * than it is. See `docs/SECURITY.md` for the threat model this implies.
 *
 * Consequences, stated plainly:
 *
 *  - no protection against an attacker who is already impersonating the peer at the Bluetooth
 *    layer, which is a stronger attacker than this scheme defends against;
 *  - **no forward secrecy.** The session key is reproducible from the two identity keys, so
 *    disclosure of a private key later exposes the traffic it protected. A per-message
 *    ephemeral key would fix that and is not implemented;
 *  - no replay protection at this layer. Replay is handled where it matters, in
 *    `MessageRepository`, by the message id.
 *
 * ## Why the private half cannot be read
 *
 * The key pair is generated by the `AndroidKeyStore` provider, so the private key is generated
 * and used inside the TEE or StrongBox and is never returned to the process. Only the public
 * half is exportable, and only it is sent. That is what makes the public key safe to put on the
 * radio.
 *
 * ## Why one alias and no rotation
 *
 * The AES key in `EncryptionManager` carries generations because a queued message may outlive
 * a rotation. An identity key cannot be rotated the same way: changing it invalidates agreement
 * with the peer and would need a re-handshake, which is a protocol change rather than a
 * configuration one. There is exactly one alias and re-pinning the device is the rotation
 * story. Recorded as a limitation rather than silently omitted.
 *
 * ## Testability
 *
 * None of this file is unit tested, because `AndroidKeyStore` does not exist on the JVM and
 * Robolectric cannot be fetched offline. That is the same gap `docs/TESTING.md` records for
 * `EncryptionManager`. What *is* tested is everything around it: the derivation
 * ([HkdfTest]), the cipher ([SessionCryptoTest]), and the handshake codec ([PeerHelloTest]).
 * The untested middle is this file's `doPhase`, and `docs/TESTING.md` says so rather than
 * implying otherwise.
 */
class IdentityKey(
    private val alias: String = DEFAULT_IDENTITY_ALIAS,
) {

    /**
     * In the class body rather than the constructor parameter list.
     *
     * Kotlin does not allow `by lazy` on a primary constructor parameter -- lazy needs a
     * property with somewhere to cache the value, and a constructor parameter has no storage of
     * its own. `EncryptionManager` does the same thing for the same reason.
     */
    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
    }

    /** Whether a key pair already exists, without creating one. */
    fun hasKeyPair(): Boolean = runCatching { keyStore.containsAlias(alias) }.getOrDefault(false)

    /**
     * Create the key pair if it is missing.
     *
     * @return true if a pair is present afterwards. False means the Keystore refused, and the
     *   app can still run as a reader of its own database but cannot take part in a
     *   conversation -- so the caller must say so rather than carry on.
     */
    fun ensureKeyPair(): Boolean {
        if (hasKeyPair()) return true
        return runCatching {
            val generator = KeyPairGenerator.getInstance(KEY_ALGORITHM, KEYSTORE_PROVIDER)
            generator.initialize(
                KeyGenParameterSpec.Builder(
                    alias,
                    KeyProperties.PURPOSE_AGREE_KEY,
                )
                    .setAlgorithmParameterSpec(ECGenParameterSpec(CURVE))
                    // No user authentication requirement: a peer must be able to read a
                    // message while the phone is locked, or a conversation silently stops
                    // working the moment the screen goes off. Stated in SECURITY.md because it
                    // is a deliberate trade, not an oversight.
                    .build(),
            )
            generator.generateKeyPair()
            true
        }.getOrDefault(false)
    }

    /**
     * This device's public key, hex encoded.
     *
     * @return the X.509 `SubjectPublicKeyInfo`, or null if no pair exists or the Keystore
     *   would not return it. Null is the normal "cannot agree" answer and callers must treat it
     *   as a refusal, not as an empty key.
     */
    fun publicKeyHex(): String? = runCatching {
        val certificate = keyStore.getCertificate(alias) ?: return null
        val encoded = certificate.publicKey.encoded ?: return null
        Hex.encode(encoded)
    }.getOrNull()

    /**
     * Agree a message key with [peerPublicKeyHex].
     *
     * @param conversationId the conversation both devices computed identically, which is what
     *   scopes the resulting key.
     * @return the session key, or null for any failure at all: a malformed key, a key on the
     *   wrong curve, a missing local private key, a Keystore that refused the operation. All of
     *   them mean the same thing to a caller -- no key, so do not send -- and none of them is
     *   worth distinguishing in the UI.
     */
    fun agree(peerPublicKeyHex: String, conversationId: String): SecretKey? {
        if (!ensureKeyPair()) return null

        val peerBytes = Hex.decode(peerPublicKeyHex) ?: return null
        if (peerBytes.size > MAX_PUBLIC_KEY_BYTES) return null

        val peer = runCatching {
            KeyFactory.getInstance(KEY_ALGORITHM).generatePublic(X509EncodedKeySpec(peerBytes))
        }.getOrNull() ?: return null

        if (!isAcceptableCurve(peer)) return null

        val privateKey = runCatching { keyStore.getKey(alias, null) }.getOrNull() ?: return null

        val secret = runCatching {
            KeyAgreement.getInstance(KEY_AGREEMENT, KEYSTORE_PROVIDER).run {
                init(privateKey)
                doPhase(peer, true)
                // Handed straight to the derivation, which zeroes it. It is never held in a
                // field or written anywhere.
                generateSecret()
            }
        }.getOrNull() ?: return null

        return SessionKeys.derive(secret, conversationId)
    }

    /**
     * Whether a received public key is one this app will agree with.
     *
     * `doPhase` already rejects a key that is not on the curve, so this is not the only line of
     * defence. It exists because the failure is otherwise opaque: an EC key on P-384 or P-521
     * is a perfectly valid key that would otherwise be accepted here and then produce a shared
     * secret of a length neither side expected.
     */
    private fun isAcceptableCurve(key: PublicKey): Boolean {
        if (key.algorithm != KEY_ALGORITHM) return false
        val ec = key as? ECPublicKey ?: return false
        val bits = ec.params.curve.field.fieldSize
        return bits in EXPECTED_FIELD_BITS.rangeTo(EXPECTED_FIELD_BITS)
    }

    companion object {
        private const val KEY_ALGORITHM = "EC"
        private const val KEY_AGREEMENT = "ECDH"
        private const val CURVE = "secp256r1"
        private const val EXPECTED_FIELD_BITS = 256

        /**
         * A P-256 `SubjectPublicKeyInfo` is about 91 bytes.
         *
         * The ceiling is roughly double that, which leaves room for a future curve while still
         * refusing to hand an arbitrary megabyte from the radio to the KeyFactory.
         */
        const val MAX_PUBLIC_KEY_BYTES = 192
    }
}